import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";

export function externalT3Guide(binary = process.execPath, home = homedir()): string {
  const connector = resolve(dirname(binary), "bruv-claude-compat");
  const agent = join(home, ".bruv", "agent");
  const sdk = join(home, ".bruv", "claude-compat-sdk");
  return [
    "Bruv + T3 Code",
    "==============",
    "Setup guide only. This command does not install, launch or configure anything.",
    "",
    "1. Install the matched Bruv pair",
    "   Stop active sessions before installing or replacing binaries.",
    "",
    "   curl -fsSL 'https://raw.githubusercontent.com/tnfssc/bruv/develop/scripts/install.sh' | sh",
    "",
    "   The installer verifies bruv + bruv-claude-compat in ~/.local/bin.",
    "   Keep them together and put ~/.local/bin on PATH. Check:",
    "",
    "     command -v bruv",
    "     command -v bruv-claude-compat",
    "     bruv --version",
    "     bruv-claude-compat --bruv-version",
    "     bruv-claude-compat --version",
    "",
    "   Bruv and --bruv-version must match. Connector --version is only Bruv connector",
    "   (no semver), not an installed Claude Code version. SDK init stays 2.1.280.",
    "   T3 treats the CLI version as unknown: no latest-Claude update candidate.",
    "   Version-gated built-in Claude models are filtered; a separate too-old model",
    "   advisory can remain. Your custom Bruv provider/id models stay available.",
    "",
    "2. Configure your provider in ordinary Bruv",
    "   Run bruv in your project. Use /login, then /model; try a small prompt.",
    "   Same OS user: CLI and connector share auth, models, settings and resources:",
    "",
    "     " + agent,
    "",
    "   No extra login or credential copying. Shared settings affect both.",
    "   SDK history below is separate: native transcripts, not credentials or",
    "   ordinary CLI history. Keep provider keys out of T3 messages and fields.",
    "",
    "3. Install official T3 and launch normally",
    "   Get T3 separately and verify its published checksums:",
    "     https://github.com/pingdotgg/t3code/releases",
    "   Open the desktop app normally, or run:",
    "     t3",
    "   No custom launch arguments or parent/server/global CLAUDE_CONFIG_DIR.",
    "   Do not change HOME or ordinary Claude state to work around setup.",
    "",
    "4. Add a separate provider instance named Bruv",
    "   Settings > Providers > + (Add provider): select Claude, then Next.",
    "   On Identity, name it Bruv (not Claude); use a unique ID, e.g. bruv.",
    "   Click Next for Config, enter the paths below, then Add instance.",
    "   Claude is the protocol slot, NOT Claude Code or an Anthropic login.",
    "   Leave your existing Claude instance untouched. Set and save:",
    "",
    "     Binary path:",
    "       " + connector,
    "     SDK history home (homePath / CLAUDE_CONFIG_DIR path):",
    "       " + sdk,
    "     Launch arguments: leave empty",
    "",
    "   Use absolute paths on the connector machine, not literal ~ or $HOME.",
    "   History home is instance-local; never use ~/.claude or the auth home.",
    "   No environment overrides needed for a normal same-user paired install.",
    "",
    "5. Add the exact custom model and set auxiliary models",
    "   Use the exact provider/model-id from your configured Bruv registry.",
    "   Click Add custom model, enter the ID, then Add. A display name is not an ID.",
    "   Hide built-in aliases with Disable all before adding your model if helpful.",
    "   Select the same ID for auxiliary title, branch and text generation.",
    "   No sonnet/opus aliases. If T3 omits a model, Bruv needs an explicit",
    "   default in shared settings; set it with /model in ordinary Bruv.",
    "",
    "6. Select Bruv and smoke-test a chat",
    "   In a new chat, select the Bruv instance AND your exact custom model.",
    "   Send: Reply with one short greeting. Do not use tools.",
    "   Check the response and auxiliary title generation. Health/readiness alone",
    "   does not verify provider access; a real successful request does.",
    "",
    "Known limits and safe updates",
    "----------------------------",
    "   T3 v0.0.46-nightly.20261004.2644 lacks the provider-scoped SDK history fix.",
    "   Basic chat may work, but native fork can fail in T3 before Bruv starts.",
    "   Full UI-only history/fork needs a T3 build with that fix; no fixed release",
    "   is promised. Do not work around it with the parent environment.",
    "",
    "   After Stop, explicitly Decline any stale approval card; do not approve it.",
    "",
    "   Never use T3's Claude login or install for Bruv. The update button can run",
    "   the connector's paired Bruv updater (not Claude) if offered by your host.",
    "   Label-only CLI identity avoids latest-Claude update candidates in researched",
    "   T3 v0.0.46-nightly.20261005.2702; built-in model advisories are separate,",
    "   not custom-model requirements. Restart T3 after updating.",
    "   Stop active Bruv/T3 sessions, update the matched pair, then restart:",
    "     bruv update --check    (read-only check)",
    "     bruv update            (CLI + connector together)",
    "     bruv-claude-compat update   (same updater; --check and --help/-h supported)",
    "   Split/custom installs need a manual paired reinstall. Update T3 separately",
    "   and recheck history-fix availability.",
    "",
    "   Startup failed? Check paths, model, ordinary Bruv auth and connector stderr",
    "   (T3 may show a generic error).",
    "",
    "Screenshot guide",
    "   https://github.com/tnfssc/bruv/blob/develop/wisdom/docs/t3-code/README.md",
    "Technical notes (separate auth homes, remote paths and other limits)",
    "   https://github.com/tnfssc/bruv/blob/develop/wisdom/claude-compat/external-t3-setup.md",
    "",
  ].join("\n");
}

/** Compatibility export; the terminal implementation lives outside T3. */
export async function runWeb(args: string[]): Promise<number> {
  return (await import("../../web/launcher")).runWeb(args);
}
